version: "3.8"
services:
  action-news_similarity:
    image: ccsamsterdam/amcat-action-news_similarity:4.0.13
    build: .
    network_mode: "host"    
    environment: # behaviour of the R script is controlled through these variables
      - amcat4_host=http://localhost/amcat
      - index=state_of_the_union
      - text_field=text
      - vector_field=embedding
      - torch_device=cuda # use 'cuda' and uncomment lines below to use GPU encoding
      - batch_size=1000
      ## Optionally only apply to some documents
      # - queries="america"
      # - "filters={\"party\": \"Republican\"}"

    # for authentication, this container needs access to the httr2 cache directory. 
    # You can find it from Python with `__import__('appdirs').user_cache_dir("amcat4py")`
    # volumes:
    #   - ~/.cache/amcat4py:/root/.cache/amcat4py # [local path]:[container path]
    
    # for use with cuda, uncomment the following lines
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
